// Generated by Scripts/import_mountains.py. Edit the reviewed catalog.json source.
import Foundation

enum MountainData {
    static let all: [Mountain] = [
        Mountain(
            name: "북한산", region: "서울 · 경기", height: 835.6,
            imageName: "bukhansan",
            summary: "북한산은 서울 · 경기에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 835.6m이며, '북한산' 항목을 기준으로 수록했습니다.",
            location: "서울특별시 강북구ㆍ성북구ㆍ종로구ㆍ은평구, 경기도 고양시ㆍ양주시",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000317")!,
            photo: MountainPhoto(
                title: "Bukhansan_(북한산).jpg",
                author: "Kellnerp",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Bukhansan_(%EB%B6%81%ED%95%9C%EC%82%B0).jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "북한산 일대의 실제 풍경")
        ),
        Mountain(
            name: "관악산", region: "서울 · 경기", height: 632.2,
            imageName: "gwanaksan",
            summary: "관악산은 서울 · 경기에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 632.2m이며, '관악산' 항목을 기준으로 수록했습니다.",
            location: "서울특별시 관악구ㆍ금천구, 경기도 안양시ㆍ과천시",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000059")!,
            photo: MountainPhoto(
                title: "Seoul.Mountain-Gwanaksan-01.jpg",
                author: "hojusaram",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Seoul.Mountain-Gwanaksan-01.jpg")!,
                license: "CC BY-SA 2.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/2.0")!,
                caption: "관악산 일대의 실제 풍경")
        ),
        Mountain(
            name: "설악산", region: "강원", height: 1708.1,
            imageName: "seoraksan",
            summary: "설악산은 강원에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1708.1m이며, '설악산' 항목을 기준으로 수록했습니다.",
            location: "강원도 속초시 설악동, 인제군 북면ㆍ인제읍, 양양군 서면ㆍ강현면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000386")!,
            photo: MountainPhoto(
                title: "Dinosaur_Ridge_of_Seoraksan.jpg",
                author: "Taewangkorea",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Dinosaur_Ridge_of_Seoraksan.jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "설악산 일대의 실제 풍경")
        ),
        Mountain(
            name: "한라산", region: "제주", height: 1947.3,
            imageName: "hallasan",
            summary: "한라산은 제주에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1947.3m이며, '한라산' 항목을 기준으로 수록했습니다.",
            location: "제주도 제주시, 서귀포시",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000661")!,
            photo: MountainPhoto(
                title: "Hallasan_Above.jpg",
                author: "LG전자",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Hallasan_Above.jpg")!,
                license: "CC BY 2.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/2.0")!,
                caption: "한라산 일대의 실제 풍경")
        ),
        Mountain(
            name: "지리산", region: "전북 · 전남 · 경남", height: 1915.4,
            imageName: "jirisaan",
            summary: "지리산은 전북 · 전남 · 경남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1915.4m이며, '지리산' 항목을 기준으로 수록했습니다.",
            location: "전라북도 남원시, 전라남도 구례군, 경상남도 하동군ㆍ산청군ㆍ함양군",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000946")!,
            photo: MountainPhoto(
                title: "Korea-Mountain-Jirisan-15.jpg",
                author: "by eimoberg",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Korea-Mountain-Jirisan-15.jpg")!,
                license: "CC BY 2.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/2.0")!,
                caption: "지리산 일대의 실제 풍경")
        ),
        Mountain(
            name: "도봉산", region: "서울 · 경기", height: 740.2,
            imageName: "dobongsan",
            summary: "도봉산은 서울 · 경기에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 740.2m이며, '도봉산(자운봉)' 항목을 기준으로 수록했습니다.",
            location: "서울특별시 도봉구, 경기도 의정부시 호원동ㆍ양주시 장흥면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000155")!,
            photo: MountainPhoto(
                title: "Mount_Dobongsan_peaks_Seoninbong_(708m),_Manjangbong_(718m),_Jaunbong_(740m)_and_Shinseondae_(730m).JPG",
                author: "Kellnerp",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Mount_Dobongsan_peaks_Seoninbong_(708m),_Manjangbong_(718m),_Jaunbong_(740m)_and_Shinseondae_(730m).JPG")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "도봉산 일대의 실제 풍경")
        ),
        Mountain(
            name: "덕유산", region: "전북 · 경남", height: 1614.2,
            imageName: "deogyusan",
            summary: "덕유산은 전북 · 경남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1614.2m이며, '덕유산(향적봉)' 항목을 기준으로 수록했습니다.",
            location: "전라북도 무주군ㆍ장수군, 경상남도 거창군ㆍ함양군",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000144")!,
            photo: MountainPhoto(
                title: "Deogyusan_from_Hyangjeok_Peak.jpg",
                author: "Yoo Chung",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Deogyusan_from_Hyangjeok_Peak.jpg")!,
                license: "CC BY-SA 2.5",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/2.5")!,
                caption: "덕유산 일대의 실제 풍경")
        ),
        Mountain(
            name: "오대산", region: "강원", height: 1565.4,
            imageName: "odaesan",
            summary: "오대산은 강원에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1565.4m이며, '오대산' 항목을 기준으로 수록했습니다.",
            location: "강원도 평창군 진부면, 홍천군 내면, 강릉시 연곡면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000455")!,
            photo: MountainPhoto(
                title: "Birobong_Peak.jpg",
                author: "Lcarrion88",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Birobong_Peak.jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "오대산 일대의 실제 풍경")
        ),
        Mountain(
            name: "소백산", region: "충북 · 경북", height: 1439.7,
            imageName: "sobaeksan",
            summary: "소백산은 충북 · 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1439.7m이며, '소백산' 항목을 기준으로 수록했습니다.",
            location: "경상북도 영주시 풍기읍, 충청북도 단양군 단양읍",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000397")!,
            photo: MountainPhoto(
                title: "Sobaeksan.jpg",
                author: "Seonghyeon5836",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Sobaeksan.jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "소백산 일대의 실제 풍경")
        ),
        Mountain(
            name: "태백산", region: "강원 · 경북", height: 1566.7,
            imageName: "taebaeksan",
            summary: "태백산은 강원 · 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1566.7m이며, '태백산' 항목을 기준으로 수록했습니다.",
            location: "강원도 태백시, 경상북도 봉화군 석포면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000638")!,
            photo: MountainPhoto(
                title: "Taebaeksan_main_peaks_from_Munsubong.jpg",
                author: "Dcpeets",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Taebaeksan_main_peaks_from_Munsubong.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "태백산 일대의 실제 풍경")
        ),
        Mountain(
            name: "치악산", region: "강원", height: 1282.0,
            imageName: "chiaksan",
            summary: "치악산은 강원에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1282m이며, '치악산' 항목을 기준으로 수록했습니다.",
            location: "강원도 원주시, 횡성군, 영월군",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000628")!,
            photo: MountainPhoto(
                title: "Chiaksan_as_seen_from_Birobong_Peak.jpg",
                author: "Ashy Minivet",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Chiaksan_as_seen_from_Birobong_Peak.jpg")!,
                license: "CC0",
                licenseURL: URL(string: "http://creativecommons.org/publicdomain/zero/1.0/deed.en")!,
                caption: "치악산 일대의 실제 풍경")
        ),
        Mountain(
            name: "월악산", region: "충북", height: 1095.3,
            imageName: "woraksan",
            summary: "월악산은 충북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1095.3m이며, '월악산' 항목을 기준으로 수록했습니다.",
            location: "충청북도 제천시 한수면, 덕산면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000505")!,
            photo: MountainPhoto(
                title: "Mount_Worak_Korea_242.jpg",
                author: "Rhythm",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Mount_Worak_Korea_242.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "월악산 일대의 실제 풍경")
        ),
        Mountain(
            name: "속리산", region: "충북 · 경북", height: 1058.4,
            imageName: "songnisan",
            summary: "속리산은 충북 · 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1058.4m이며, '속리산' 항목을 기준으로 수록했습니다.",
            location: "경상북도 상주시 화북면, 충청북도 보은군 내속리면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000399")!,
            photo: MountainPhoto(
                title: "Gwaneum_Peak_at_Songnisan.jpg",
                author: "Yoo Chung",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Gwaneum_Peak_at_Songnisan.jpg")!,
                license: "CC BY-SA 2.5",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/2.5")!,
                caption: "속리산 일대의 실제 풍경")
        ),
        Mountain(
            name: "계룡산", region: "충남 · 대전", height: 846.5,
            imageName: "gyeryongsan",
            summary: "계룡산은 충남 · 대전에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 846.5m이며, '계룡산' 항목을 기준으로 수록했습니다.",
            location: "대전광역시, 충청남도 공주시 계룡면ㆍ논산시 상월면ㆍ계룡시 신도안면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000040")!,
            photo: MountainPhoto(
                title: "Mount_Gyeryong_from_Jang-gun_peak.jpg",
                author: "Yoo Chung",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Mount_Gyeryong_from_Jang-gun_peak.jpg")!,
                license: "CC BY-SA 2.5",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/2.5")!,
                caption: "계룡산 일대의 실제 풍경")
        ),
        Mountain(
            name: "가야산", region: "경북 · 경남", height: 1432.6,
            imageName: "gayasan",
            summary: "가야산은 경북 · 경남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1432.6m이며, '가야산' 항목을 기준으로 수록했습니다.",
            location: "경상남도 합천군ㆍ거창군, 경상북도 성주군",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000009")!,
            photo: MountainPhoto(
                title: "GayaSanghwangbong.jpg",
                author: "Straitgate at English Wikipedia",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:GayaSanghwangbong.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "http://creativecommons.org/licenses/by-sa/3.0/")!,
                caption: "가야산 일대의 실제 풍경")
        ),
        Mountain(
            name: "내장산", region: "전북", height: 763.5,
            imageName: "naejangsan",
            summary: "내장산은 전북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 763.5m이며, '내장산' 항목을 기준으로 수록했습니다.",
            location: "전라북도 정읍시 내장동, 순창군 복흥면ㆍ쌍치면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000112")!,
            photo: MountainPhoto(
                title: "Najaengsan.JPG",
                author: "Café Bene",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Najaengsan.JPG")!,
                license: "CC0",
                licenseURL: URL(string: "http://creativecommons.org/publicdomain/zero/1.0/deed.en")!,
                caption: "내장산 일대의 실제 풍경")
        ),
        Mountain(
            name: "무등산", region: "전남 · 광주", height: 1186.8,
            imageName: "mudeungsan",
            summary: "무등산은 전남 · 광주에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1186.8m이며, '무등산' 항목을 기준으로 수록했습니다.",
            location: "광주광역시 동구, 전라남도 담양군 남면ㆍ화순군 이서면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000225")!,
            photo: MountainPhoto(
                title: "Mt_Mudeungsan_-_panoramio.jpg",
                author: "gary4now",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Mt_Mudeungsan_-_panoramio.jpg")!,
                license: "CC BY 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/3.0")!,
                caption: "무등산 일대의 실제 풍경")
        ),
        Mountain(
            name: "월출산", region: "전남", height: 810.7,
            imageName: "wolchulsan",
            summary: "월출산은 전남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 810.7m이며, '월출산' 항목을 기준으로 수록했습니다.",
            location: "전라남도 영암군 영암읍ㆍ군서면ㆍ학산면, 강진군 성전면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000507")!,
            photo: MountainPhoto(
                title: "Wolchulsan_mountain_peak.jpg",
                author: "No machine-readable author provided. Fbjon assumed (based on copyright claims).",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Wolchulsan_mountain_peak.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "http://creativecommons.org/licenses/by-sa/3.0/")!,
                caption: "월출산 일대의 실제 풍경")
        ),
        Mountain(
            name: "주왕산", region: "경북", height: 722.1,
            imageName: "juwangsan",
            summary: "주왕산은 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 722.1m이며, '주왕산' 항목을 기준으로 수록했습니다.",
            location: "경상북도 청송군 청송읍ㆍ부동면, 영덕군 지품면ㆍ달산면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000573")!,
            photo: MountainPhoto(
                title: "주산지-1.jpg",
                author: "Contax3",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:%EC%A3%BC%EC%82%B0%EC%A7%80-1.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "주왕산국립공원 주산지의 풍경")
        ),
        Mountain(
            name: "두륜산", region: "전남", height: 700.0,
            imageName: "duryunsan",
            summary: "두륜산은 전남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 700m이며, '두륜산' 항목을 기준으로 수록했습니다.",
            location: "전라남도 해남군 삼산면ㆍ북일면ㆍ북평면ㆍ현산면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000165")!,
            photo: MountainPhoto(
                title: "Daeheungsa 11-03949.JPG",
                author: "steve46814",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Daeheungsa_11-03949.JPG")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "두륜산 자락의 대흥사 일대")
        ),
        Mountain(
            name: "팔공산", region: "경북 · 대구", height: 1192.3,
            imageName: "palgongsan",
            summary: "팔공산은 경북 · 대구에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1192.3m이며, '팔공산' 항목을 기준으로 수록했습니다.",
            location: "경상북도 군위군 부계면, 영천시 신녕면, 대구광역시 동구",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000651")!,
            photo: MountainPhoto(
                title: "Korea-Daegu-Palgongsan-01.jpg",
                author: "mumutia",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Korea-Daegu-Palgongsan-01.jpg")!,
                license: "CC BY 2.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/2.0")!,
                caption: "팔공산 일대의 실제 풍경")
        ),
        Mountain(
            name: "금정산", region: "경남 · 부산", height: 800.8,
            imageName: "geumjeongsan",
            summary: "금정산은 경남 · 부산에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 800.8m이며, '금정산' 항목을 기준으로 수록했습니다.",
            location: "부산광역시 금정구ㆍ북구, 경상남도 양산시",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000094")!,
            photo: MountainPhoto(
                title: "금정산.jpg",
                author: "Jocelyndurrey",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:%EA%B8%88%EC%A0%95%EC%82%B0.jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "금정산 일대의 실제 풍경")
        ),
        Mountain(
            name: "가지산", region: "경북 · 경남 · 울산", height: 1240.9,
            imageName: "gajisan",
            summary: "가지산은 경북 · 경남 · 울산에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1240.9m이며, '가지산' 항목을 기준으로 수록했습니다.",
            location: "울산광역시, 경상북도 청도군, 경상남도 밀양시",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000012")!,
            photo: MountainPhoto(
                title: "Yeongnam Alps in Summer.jpg",
                author: "Lcarrion88",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Yeongnam_Alps_in_Summer.jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "가지산도립공원의 여름 풍경")
        ),
        Mountain(
            name: "신불산", region: "울산", height: 1159.3,
            imageName: "sinbulsan",
            summary: "신불산은 울산에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1159.3m이며, '신불산' 항목을 기준으로 수록했습니다.",
            location: "울산광역시 울주군 삼남면ㆍ상북면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000422")!,
            photo: MountainPhoto(
                title: "신불산.jpg",
                author: "Kiduk Yang",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:%EC%8B%A0%EB%B6%88%EC%82%B0.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "신불산 산악 풍경")
        ),
        Mountain(
            name: "천성산", region: "경남", height: 920.2,
            imageName: "cheonseongsan",
            summary: "천성산은 경남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 920.2m이며, '천성산' 항목을 기준으로 수록했습니다.",
            location: "경상남도 양산시 하북면, 상북면, 웅상읍",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000601")!,
            photo: MountainPhoto(
                title: "Cheonsung.JPG",
                author: "Rhythm",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Cheonsung.JPG")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "천성산 일대의 실제 풍경")
        ),
        Mountain(
            name: "비슬산", region: "경북 · 대구", height: 1083.4,
            imageName: "biseulsan",
            summary: "비슬산은 경북 · 대구에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1083.4m이며, '비슬산' 항목을 기준으로 수록했습니다.",
            location: "대구광역시 달성군 옥포면ㆍ유가면ㆍ가창면, 경상북도 청도군 각북면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000329")!,
            photo: MountainPhoto(
                title: "Korea-Mount_Biseul-Azalea_Valley-01.jpg",
                author: "by Caroline Knox at flickr",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Korea-Mount_Biseul-Azalea_Valley-01.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "비슬산 일대의 실제 풍경")
        ),
        Mountain(
            name: "황매산", region: "경남", height: 1113.1,
            imageName: "hwangmaesan",
            summary: "황매산은 경남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1113.1m이며, '황매산' 항목을 기준으로 수록했습니다.",
            location: "경상남도 합천군 대병면, 가회면, 산청군 차황면.",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000684")!,
            photo: MountainPhoto(
                title: "Hwangmaesan_Mountain_in_autumn.jpg",
                author: "Choi2451",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Hwangmaesan_Mountain_in_autumn.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "황매산 일대의 실제 풍경")
        ),
        Mountain(
            name: "대둔산", region: "충남 · 전북", height: 879.1,
            imageName: "daedunsan",
            summary: "대둔산은 충남 · 전북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 879.1m이며, '대둔산' 항목을 기준으로 수록했습니다.",
            location: "충청남도 논산시 벌곡면ㆍ금산군 진산면, 전라북도 완주군 온주면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000131")!,
            photo: MountainPhoto(
                title: "Chilseongbong_at_Daedunsan.jpg",
                author: "Yoo Chung",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Chilseongbong_at_Daedunsan.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "대둔산 일대의 실제 풍경")
        ),
        Mountain(
            name: "마이산", region: "전북", height: 687.4,
            imageName: "maisan",
            summary: "마이산은 전북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 687.4m이며, '마이산' 항목을 기준으로 수록했습니다.",
            location: "전라북도 진안군 진안읍ㆍ마령면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000176")!,
            photo: MountainPhoto(
                title: "Maisan.jpg",
                author: "Joachim Dirauf",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Maisan.jpg")!,
                license: "CC BY 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/3.0")!,
                caption: "마이산 일대의 실제 풍경")
        ),
        Mountain(
            name: "선운산", region: "전북", height: 334.7,
            imageName: "seonunsan",
            summary: "선운산은 전북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 334.7m이며, '선운산' 항목을 기준으로 수록했습니다.",
            location: "전라북도 고창군 아산면ㆍ심원면ㆍ해리면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000383")!,
            photo: MountainPhoto(
                title: "선운산.jpg",
                author: "Seong Ilhan",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:%EC%84%A0%EC%9A%B4%EC%82%B0.jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "선운산 일대의 실제 풍경")
        ),
        Mountain(
            name: "소요산", region: "경기", height: 587.5,
            imageName: "soyosan",
            summary: "소요산은 경기에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 587.5m이며, '소요산' 항목을 기준으로 수록했습니다.",
            location: "경기도 동두천시, 포천시 신북면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000398")!,
            photo: MountainPhoto(
                title: "Soyosan.jpg",
                author: "Jjw",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Soyosan.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "소요산 일대의 실제 풍경")
        ),
        Mountain(
            name: "마니산", region: "인천", height: 472.1,
            imageName: "manisan",
            summary: "마니산은 인천에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 472.1m이며, '마니산' 항목을 기준으로 수록했습니다.",
            location: "인천광역시 강화군 화도면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000171")!,
            photo: MountainPhoto(
                title: "Mt_mani_2.jpg",
                author: "w:ko:Jtm71",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Mt_mani_2.jpg")!,
                license: "CC BY 2.0 kr",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/2.0/kr/deed.en")!,
                caption: "마니산 일대의 실제 풍경")
        ),
        Mountain(
            name: "감악산", region: "경기", height: 674.9,
            imageName: "gamaksan",
            summary: "감악산은 경기에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 674.9m이며, '감악산' 항목을 기준으로 수록했습니다.",
            location: "경기도 양주시 남면, 연천군 전곡읍, 파주시 적성면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000024")!,
            photo: MountainPhoto(
                title: "Gamaksan_Bridge_1.jpg",
                author: "AnonymousUnknown author",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Gamaksan_Bridge_1.jpg")!,
                license: "CC0",
                licenseURL: URL(string: "http://creativecommons.org/publicdomain/zero/1.0/deed.en")!,
                caption: "감악산 계곡을 잇는 출렁다리")
        ),
        Mountain(
            name: "유명산", region: "경기", height: 864.0,
            imageName: "yumyeongsan",
            summary: "유명산은 경기에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 864m이며, '유명산' 항목을 기준으로 수록했습니다.",
            location: "경기도 가평군 설악면, 양평군 옥천면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000514")!,
            photo: MountainPhoto(
                title: "Peak_of_Yumyeong_Mountain.JPG",
                author: "G43",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Peak_of_Yumyeong_Mountain.JPG")!,
                license: "CC BY 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/3.0")!,
                caption: "유명산 일대의 실제 풍경")
        ),
        Mountain(
            name: "삼악산", region: "강원", height: 655.8,
            imageName: "samaksan",
            summary: "삼악산은 강원에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 655.8m이며, '삼악산' 항목을 기준으로 수록했습니다.",
            location: "강원도 춘천시 서면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000702")!,
            photo: MountainPhoto(
                title: "삼악산_정상_3.jpg",
                author: "Sadopaul",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:%EC%82%BC%EC%95%85%EC%82%B0_%EC%A0%95%EC%83%81_3.jpg")!,
                license: "CC BY 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/4.0")!,
                caption: "삼악산 일대의 실제 풍경")
        ),
        Mountain(
            name: "민주지산", region: "충북 · 전북 · 경북", height: 1241.7,
            imageName: "minjujisan",
            summary: "민주지산은 충북 · 전북 · 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1241.7m이며, '민주지산' 항목을 기준으로 수록했습니다.",
            location: "충청북도 영동군 상촌면ㆍ용화면, 전라북도 무주군 설천면, 경상북도 김천시 부항면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000247")!,
            photo: MountainPhoto(
                title: "Minjujisan_Muju.jpg",
                author: "Ha98574 (Min's)",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Minjujisan_Muju.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "민주지산 일대의 실제 풍경")
        ),
        Mountain(
            name: "청량산", region: "경북", height: 869.7,
            imageName: "cheongnyangsan",
            summary: "청량산은 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 869.7m이며, '청량산' 항목을 기준으로 수록했습니다.",
            location: "경상북도 봉화군 명호면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000613")!,
            photo: MountainPhoto(
                title: "Korea-Bonghwa_County-Mount_Cheongnyangsan-01.jpg",
                author: "Robert at w:Picasa",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Korea-Bonghwa_County-Mount_Cheongnyangsan-01.jpg")!,
                license: "CC BY 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/3.0")!,
                caption: "청량산 일대의 실제 풍경")
        ),
        Mountain(
            name: "금오산", region: "경북", height: 976.5,
            imageName: "geumosan",
            summary: "금오산은 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 976.5m이며, '금오산' 항목을 기준으로 수록했습니다.",
            location: "경상북도 구미시, 칠곡군 북삼읍, 김천시 남면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000092")!,
            photo: MountainPhoto(
                title: "Geumomtcablecar.jpg",
                author: "Kimhs5400(블루시티)",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Geumomtcablecar.jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "구미 금오산의 케이블카와 산세")
        ),
        Mountain(
            name: "모악산", region: "전북", height: 795.2,
            imageName: "moaksan",
            summary: "모악산은 전북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 795.2m이며, '모악산' 항목을 기준으로 수록했습니다.",
            location: "전라북도 김제시 금산면ㆍ전주시 완산구ㆍ완주군 구이면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000219")!,
            photo: MountainPhoto(
                title: "모악산.jpg",
                author: "Seong Ilhan",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:%EB%AA%A8%EC%95%85%EC%82%B0.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "모악산 일대의 실제 풍경")
        ),
        Mountain(
            name: "두타산", region: "강원", height: 1357.0,
            imageName: "dutasan",
            summary: "두타산은 강원에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1357m이며, '두타산' 항목을 기준으로 수록했습니다.",
            location: "강원도 동해시 삼화동, 삼척시 미로면ㆍ하장면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000167")!,
            photo: MountainPhoto(
                title: "Mou0020.jpg",
                author: "eimoberg",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Mou0020.jpg")!,
                license: "CC BY 2.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/2.0")!,
                caption: "두타산 일대의 실제 풍경")
        ),
        Mountain(
            name: "내연산", region: "경북", height: 711.3,
            imageName: "naeyeonsan",
            summary: "내연산은 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 711.3m이며, '내연산' 항목을 기준으로 수록했습니다.",
            location: "경상북도 포항시 송라면ㆍ청하면ㆍ죽장면, 영덕군 남정면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000111")!,
            photo: MountainPhoto(
                title: "Naeyeonsan.jpg",
                author: "Raki_Man",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Naeyeonsan.jpg")!,
                license: "CC BY 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/3.0")!,
                caption: "내연산 풍경")
        ),
        Mountain(
            name: "화왕산", region: "경남", height: 757.7,
            imageName: "hwawangsan",
            summary: "화왕산은 경남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 757.7m이며, '화왕산' 항목을 기준으로 수록했습니다.",
            location: "경상남도 창녕군 창녕읍 옥천리 일대",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000681")!,
            photo: MountainPhoto(
                title: "Changnyeong Hwawangsan wide.jpg",
                author: "Taken by User:Visviva and released into the public domain.",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Changnyeong_Hwawangsan_wide.jpg")!,
                license: "Public domain",
                licenseURL: URL(string: "https://creativecommons.org/publicdomain/mark/1.0/")!,
                caption: "창녕 화왕산 전경")
        ),
        Mountain(
            name: "성인봉", region: "경북", height: 986.5,
            imageName: "seonginbong",
            summary: "성인봉은 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 986.5m이며, '성인봉' 항목을 기준으로 수록했습니다.",
            location: "경상북도 울릉군 울릉읍 서면ㆍ북면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000389")!,
            photo: MountainPhoto(
                title: "Ulleung_island_from_above.jpg",
                author: "NASA Landsat7 image",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Ulleung_island_from_above.jpg")!,
                license: "Public domain",
                licenseURL: URL(string: "https://creativecommons.org/publicdomain/mark/1.0/")!,
                caption: "성인봉이 자리한 울릉도의 항공 전경")
        ),
        Mountain(
            name: "적상산", region: "전북", height: 1030.6,
            imageName: "jeoksangsan",
            summary: "적상산은 전북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1030.6m이며, '적상산' 항목을 기준으로 수록했습니다.",
            location: "전라북도 무주군 적상면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000548")!,
            photo: MountainPhoto(
                title: "MJ-JS-JSG14.jpg",
                author: "Dittwjfsdgkvkdjg",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:MJ-JS-JSG14.jpg")!,
                license: "CC BY 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by/4.0")!,
                caption: "적상산 일대의 실제 풍경")
        ),
        Mountain(
            name: "천마산", region: "경기", height: 810.3,
            imageName: "cheonmasan",
            summary: "천마산은 경기에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 810.3m이며, '천마산' 항목을 기준으로 수록했습니다.",
            location: "경기도 남양주시 오남읍, 화도읍",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000597")!,
            photo: MountainPhoto(
                title: "천마산.jpg",
                author: "한국학중앙연구원·유남해",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:%EC%B2%9C%EB%A7%88%EC%82%B0.jpg")!,
                license: "KOGL Type 1",
                licenseURL: URL(string: "http://www.kogl.or.kr/info/licenseType1.do")!,
                caption: "천마산 풍경")
        ),
        Mountain(
            name: "화악산", region: "경기 · 강원", height: 1468.3,
            imageName: "hwaaksan",
            summary: "화악산은 경기 · 강원에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 1468.3m이며, '화악산(중봉)' 항목을 기준으로 수록했습니다.",
            location: "경기도 가평군 북면, 강원도 화천군 사내면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000679")!,
            photo: MountainPhoto(
                title: "Broadcast_Transmitter_Station_and_ROKAF_Radar_Site_in_Hwaaksan.jpg",
                author: "Wunderpoly",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Broadcast_Transmitter_Station_and_ROKAF_Radar_Site_in_Hwaaksan.jpg")!,
                license: "CC BY-SA 4.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/4.0")!,
                caption: "화악산의 송신 시설과 산악 지형")
        ),
        Mountain(
            name: "추월산", region: "전북 · 전남", height: 731.2,
            imageName: "chuwolsan",
            summary: "추월산은 전북 · 전남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 731.2m이며, '추월산' 항목을 기준으로 수록했습니다.",
            location: "전라남도 담양군 용면, 전라북도 순창군 복흥면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000622")!,
            photo: MountainPhoto(
                title: "Photo 2025-06-01-폭포사진-하늘과폭포-추월산.jpg",
                author: "레이저마인드",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Photo_2025-06-01-%ED%8F%AD%ED%8F%AC%EC%82%AC%EC%A7%84-%ED%95%98%EB%8A%98%EA%B3%BC%ED%8F%AD%ED%8F%AC-%EC%B6%94%EC%9B%94%EC%82%B0.jpg")!,
                license: "CC0",
                licenseURL: URL(string: "http://creativecommons.org/publicdomain/zero/1.0/deed.en")!,
                caption: "추월산의 폭포와 숲")
        ),
        Mountain(
            name: "미륵산", region: "경남", height: 458.4,
            imageName: "mireuksan",
            summary: "미륵산은 경남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 458.4m이며, '미륵산' 항목을 기준으로 수록했습니다.",
            location: "경상남도 통영시 산양읍ㆍ봉평동",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000242")!,
            photo: MountainPhoto(
                title: "Tongyeong Mt.Miruek Path.jpg",
                author: "Asfreeas",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Tongyeong_Mt.Miruek_Path.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "통영 미륵산의 숲길")
        ),
        Mountain(
            name: "남산 (경주)", region: "경북", height: 495.1,
            imageName: "namsan-gyeongju",
            summary: "남산 (경주)은 경북에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 495.1m이며, '남산' 항목을 기준으로 수록했습니다.",
            location: "경상북도 경주시 남산동ㆍ내남면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000108")!,
            photo: MountainPhoto(
                title: "경주 남산일원 용장골 등산로 인근 서쪽상공(동쪽으로 조망).jpg",
                author: "고도보존육성과",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:%EA%B2%BD%EC%A3%BC_%EB%82%A8%EC%82%B0%EC%9D%BC%EC%9B%90_%EC%9A%A9%EC%9E%A5%EA%B3%A8_%EB%93%B1%EC%82%B0%EB%A1%9C_%EC%9D%B8%EA%B7%BC_%EC%84%9C%EC%AA%BD%EC%83%81%EA%B3%B5(%EB%8F%99%EC%AA%BD%EC%9C%BC%EB%A1%9C_%EC%A1%B0%EB%A7%9D).jpg")!,
                license: "KOGL Type 1",
                licenseURL: URL(string: "http://www.kogl.or.kr/info/licenseType1.do")!,
                caption: "경주 남산 용장골 일대의 산세")
        ),
        Mountain(
            name: "금산 (남해)", region: "경남", height: 704.9,
            imageName: "geumsan-namhae",
            summary: "금산 (남해)은 경남에 위치한 산림청 선정 100대 명산입니다. 공식 목록의 산높이는 704.9m이며, '금산' 항목을 기준으로 수록했습니다.",
            location: "경상남도 남해군 상주면ㆍ이동면ㆍ삼동면",
            sourceURL: URL(string: "https://www.forest.go.kr/kfsweb/kfi/kfs/foreston/main/contents/ClbngManage/selectMntnInfoDetail.do?mn=AR02_02_05_01&mntnId=20000934")!,
            photo: MountainPhoto(
                title: "Geumsan of Namhae, Korea.jpg",
                author: "RYU Cheol (Ryuch)",
                sourceURL: URL(string: "https://commons.wikimedia.org/wiki/File:Geumsan_of_Namhae,_Korea.jpg")!,
                license: "CC BY-SA 3.0",
                licenseURL: URL(string: "https://creativecommons.org/licenses/by-sa/3.0")!,
                caption: "남해 금산의 산악 풍경")
        ),
    ]
}
