"""Rebuild the reviewed 50-mountain offline catalog.

Run: python3 Scripts/import_mountains.py
Existing assets are reused. Missing photographs are downloaded only with --download.
Source facts and per-image licenses are frozen in CatalogSources/catalog.json.
No API keys or third-party Python packages are required.
"""
import argparse, hashlib, json, subprocess, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / 'New Group/Sangil'
SOURCES = ROOT / 'Documentation/CatalogSources'
MANIFEST = SOURCES / 'catalog.json'

def quoted(value):
    return json.dumps(value, ensure_ascii=False).replace('\\/', '/')

def download(photo, destination):
    url=photo['downloadURL'].split('?')[0].replace('thumb.wikimedia.org','upload.wikimedia.org')
    temporary=destination.with_suffix('.download')
    result=subprocess.run(['curl','-f','-sS','-L','--max-time','60','--retry','2','--retry-delay','5',url,'-o',str(temporary)])
    if result.returncode:
        subprocess.run(['curl','-f','-sS','-L','--max-time','60',photo['originalURL'].split('?')[0],'-o',str(temporary)],check=True)
    if temporary.read_bytes()[:2] != b'\xff\xd8': raise ValueError(f'Not a JPEG: {destination.name}')
    subprocess.run(['sips','-Z','1280',str(temporary),'--out',str(destination)],check=True,capture_output=True)
    temporary.unlink()
    time.sleep(1)

def main():
    args=argparse.ArgumentParser()
    args.add_argument('--download',action='store_true')
    options=args.parse_args()
    data=json.loads(MANIFEST.read_text())
    mountains=data['mountains']
    assert len(mountains)==50
    assert len({m['id'] for m in mountains})==50
    assert len({m['photo']['pageURL'] for m in mountains})==50
    swift=['// Generated by Scripts/import_mountains.py. Edit the reviewed catalog.json source.','import Foundation','','enum MountainData {','    static let all: [Mountain] = [']
    credits=['# Sangil mountain photography','',f"Source review: {data['retrievedOn']}",'','All images are resized to a maximum of 1280 pixels. UI cropping does not change the source asset. Each photograph retains its own license; the application code is not licensed by these image licenses.','']
    total=0
    for index,m in enumerate(mountains):
        photo=m['photo']; key=m['id']
        assert photo['author'] and photo['licenseURL'] and m['sourceURL'].split('mntnId=')[-1]
        folder=APP/'Assets.xcassets'/f'{key}.imageset'; folder.mkdir(exist_ok=True)
        destination=folder/'mountain.jpg'
        cached=SOURCES/'photos'/f'{key}.jpg'
        if not destination.exists():
            if cached.exists(): destination.write_bytes(cached.read_bytes())
            elif options.download: download(photo,destination)
            else: raise FileNotFoundError(f'{key}: photo missing; use --download')
        assert destination.read_bytes()[:2]==b'\xff\xd8',key
        imageHash=hashlib.sha256(destination.read_bytes()).hexdigest()
        if 'sha256' in photo and photo['sha256']!=imageHash: raise ValueError(f'Photo checksum changed: {key}; review the source before updating')
        photo['sha256']=imageHash;total+=destination.stat().st_size
        (folder/'Contents.json').write_text(json.dumps({'images':[{'filename':'mountain.jpg','idiom':'universal'}],'info':{'author':'xcode','version':1}},indent=2)+'\n')
        swift += ['        Mountain(',f'            name: {quoted(m["name"])}, region: {quoted(m["region"])}, height: {m["height"]},',f'            imageName: {quoted(key)},',f'            summary: {quoted(m["summary"])},',f'            location: {quoted(m["location"])},',f'            sourceURL: URL(string: {quoted(m["sourceURL"])})!,','            photo: MountainPhoto(',f'                title: {quoted(photo["filename"])},',f'                author: {quoted(photo["author"])},',f'                sourceURL: URL(string: {quoted(photo["pageURL"])})!,',f'                license: {quoted(photo["license"])},',f'                licenseURL: URL(string: {quoted(photo["licenseURL"])})!,',f'                caption: {quoted(photo["caption"])})', '        ),']
        credits += [f'## {m["name"]} (`{key}`)','',f'- Photographer: {photo["author"]}',f'- Work: [{photo["filename"]}]({photo["pageURL"]})',f'- License: [{photo["license"]}]({photo["licenseURL"]})',f'- Caption: {photo["caption"]}',f'- Mountain facts: [Korea Forest Service]({m["sourceURL"]})',f'- SHA-256: `{imageHash}`','']
    swift += ['    ]','}','']
    (APP/'Data/MountainData.swift').write_text('\n'.join(swift))
    (ROOT/'Documentation/PHOTO_CREDITS.md').write_text('\n'.join(credits))
    MANIFEST.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
    print(f'Validated/generated {len(mountains)} mountains and {len(mountains)} photographs ({total/1024/1024:.1f} MiB).')

if __name__=='__main__':main()
